---
- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ lvm_management_dependencies }}"
    state: present

# Only configure PV/LVM on vms or physical machines
- include_tasks: resize_pv.yml
  with_items:
    - "{{ lvm_management_devices }}"
  when:
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "containerd"

# Only configure PV/LVM on vms or physical machines
- import_tasks: configure_lvms.yml
  when:
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "containerd"
