---
- name: DEBUG - Print Partition and number
  ansible.builtin.debug:
    msg: "{{ item.partition }}{{ item.number }}"

- name: Rescan underlying block devices
  ansible.builtin.shell: echo 1 > /sys/class/block/{{ item.partition | basename }}/device/rescan
  failed_when: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: Partition info
  community.general.parted:
    device: "{{ item.partition }}"
    number: "{{ item.number }}"
  register: partinfo

- name: Set fact -> gap_kb
  ansible.builtin.set_fact:
    gap_kb: "{{ partinfo.disk.size - partinfo.partitions[vars.item.number-1].end }}"

- name: DEBUG - partition gap
  ansible.builtin.debug:
    msg: "Gap after partition {{ item.partition }}: {{ lvm_management_max_gap_kb }}kiB"

# parted does not resize: https://github.com/ansible/ansible/issues/23914
# Request resize, ack resize of partition that is in use (when requested).
# https://bugs.launchpad.net/ubuntu/+source/parted/+bug/1270203
# https://unix.stackexchange.com/a/365657
# parted allows to fix GPT only interactively
# https://bugs.launchpad.net/ubuntu/+source/parted/+bug/1490608
- name: use growpart too grow small partition to maximum
  ansible.builtin.command: 'growpart {{ item.partition }} {{ item.number }}'
  when: lvm_management_max_gap_kb < gap_kb|int

- name: Check existence of physical volume (pv)
  ansible.builtin.command: pvs "{{ item.partition }}{{ item.number }}"
  failed_when: false
  changed_when: false
  register: pvs

- name: Resize physical volume (pv)
  ansible.builtin.command: 'pvresize "{{ item.partition }}{{ item.number }}"'
  when: pvs.rc == 0
  changed_when: false
