---
molecule_exceptions:
  - variation: ubi8/9
    reason: "Packages not available"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "fedora35"
      - "fedora36"
      - "amazonlinux"
      - "rockylinux8"
      - "rockylinux9"
      - "almalinux8"
      - "almalinux9"
